# Generated by Django 2.2.6 on 2019-10-20 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191020_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity111',
            new_name='quantity',
        ),
    ]
