# Generated by Django 2.2.6 on 2019-10-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191020_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Количество'},
        ),
    ]
